name: Deploy Bento
on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Build and Deploy
        uses: bentoml/deploy-bento-action@main
        with:
          cloud_api_token: ${{ secrets.BENTOCLOUD_API_TOKEN }}
          cloud_endpoint: ${{ secrets.BENTOCLOUD_ENDPOINT }}
          deployment_name: iris-frost
